import type{Metadata}from"next";
export const metadata:Metadata={title:"TiviMate Sverige — Komplett Guide 2026 | Sverige TV",description:"Installera och konfigurera TiviMate för IPTV. Bästa IPTV-appen för Android och Firestick. Steg-för-steg med Sverige TV."};
export default function Page(){return(<main style={{maxWidth:800,margin:"0 auto",padding:"60px 20px",color:"#f0eff0",fontFamily:"system-ui,sans-serif",background:"#060407",minHeight:"100vh"}}>
<nav style={{marginBottom:24,fontSize:13,color:"#7a7a86"}}><a href="/" style={{color:"#c8a96e",textDecoration:"none"}}>Sverige TV</a> › <a href="/installation" style={{color:"#c8a96e",textDecoration:"none"}}>Installation</a> › TiviMate</nav>
<h1 style={{fontSize:"clamp(1.8rem,5vw,2.8rem)",fontWeight:900,marginBottom:12}}>TiviMate — Bästa IPTV-appen</h1>
<p style={{color:"#9898a4",marginBottom:32,lineHeight:1.7}}>TiviMate är den mest populära IPTV-appen bland svenska användare. Elegant gränssnitt, snabb EPG och stöd för 4K. Fungerar på Firestick, Android TV och Android-mobiler.</p>
<h2 style={{fontSize:"1.2rem",fontWeight:800,margin:"0 0 20px"}}>Installation på Firestick</h2>
{[["Aktivera sideloading","Inställningar → Min Fire TV → Utvecklaralternativ → Okända källor: PÅ"],["Installera Downloader","Sök och installera 'Downloader' gratis från Amazon App Store"],["Ladda ner TiviMate APK","Öppna Downloader → ange URL: tivimate.com → ladda ner APK"],["Installera och öppna","Följ installationsguiden, öppna TiviMate"],["Lägg till spellista","Välj 'Xtream Codes' → ange server, användarnamn och lösenord från Sverige TV"],["Uppdatera EPG","Inställningar → EPG → Uppdatera vid start: PÅ. Klart!"]].map(([t,d],i)=>(<div key={i} style={{display:"flex",gap:16,marginBottom:16,background:"#0b0b0d",border:"1px solid #1e1e1e",borderRadius:10,padding:"16px"}}>
<div style={{width:36,height:36,borderRadius:"50%",background:"linear-gradient(135deg,#9a1830,#7c1326)",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,fontSize:14,flexShrink:0}}>{i+1}</div>
<div><b style={{display:"block",marginBottom:4,fontSize:15}}>{t}</b><span style={{color:"#9898a4",fontSize:14,lineHeight:1.6}}>{d}</span></div></div>))}
<div style={{background:"#0d1a0d",border:"1px solid #16a34a",borderRadius:12,padding:"20px 24px",margin:"32px 0"}}>
<b style={{color:"#22c55e"}}>💡 TiviMate Premium</b>
<p style={{margin:"8px 0 0",color:"#d4d4d8",lineHeight:1.7,fontSize:14}}>Gratisversionen fungerar bra. Premium (ca 150 kr/år) lägger till: multi-skärm, inspelning, arkiv och obegränsat antal spellistor. Rekommenderas för avancerade användare.</p></div>
{[["TiviMate vs IPTV Smarters — vilket är bäst?","TiviMate är snabbare och har bättre EPG-guide. IPTV Smarters är enklare att installera (finns i Play Store). Vi rekommenderar TiviMate för bästa upplevelse."],["Varför syns inte EPG-guiden?","Gå till Inställningar → EPG → Uppdatera nu. Första laddningen tar 2–5 minuter."],["Kan jag använda TiviMate på iPhone?","Nej — TiviMate finns bara för Android/Firestick. På iPhone rekommenderar vi IPTV Smarters Pro från App Store."]].map(([q,a],i)=>(<details key={i} style={{background:"#0b0b0d",border:"1px solid #222",borderRadius:10,marginBottom:10,padding:"14px 18px"}}><summary style={{fontWeight:700,cursor:"pointer"}}>{q}</summary><p style={{marginTop:10,color:"#d4d4d8",lineHeight:1.7,fontSize:14}}>{a}</p></details>))}
<div style={{background:"#1a0a10",border:"1px solid #7c1326",borderRadius:14,padding:"28px",marginTop:40,textAlign:"center"}}><h3 style={{fontWeight:900,marginBottom:8}}>Hjälp med TiviMate-inställningar?</h3><p style={{color:"#9898a4",marginBottom:20}}>Vi konfigurerar TiviMate åt dig via WhatsApp — tar 5 minuter.</p><a href="https://wa.me/447307410512?text=Hej!+Jag+behöver+hjälp+med+TiviMate+konfiguration." target="_blank" rel="noreferrer" style={{background:"#22c55e",color:"#000",padding:"14px 28px",borderRadius:8,textDecoration:"none",fontWeight:800}}>💬 WhatsApp-support</a></div>
</main>);}
