// components/shared/countries.ts
// Multilingual community channel packages — STRATEGIC FOCUS:
// 1. ExYu (Bosnian/Serbian/Croatian) — HIGH PRIORITY per user research
// 2. Arabic — Large diaspora in Malmö, Stockholm
// 3. Turkish — Established community
// 4. Persian, Kurdish, Somali, Polish, Finnish — secondary
// 5. Spanish, Greek, Portuguese, Thai, Vietnamese, Chinese, Indian, African — long-tail

import type { Country } from "./types";

export const COUNTRIES: Country[] = [
  // ============ TIER 1: HIGH PRIORITY (per user's market research) ============
  {
    slug: "exyu",
    flag: "🇧🇦",
    name: "ExYu",
    sub: "Pink, RTS, HRT, Arena Sport",
    desc: "Komplett ExYu-paket — bosniska, serbiska, kroatiska, slovenska och makedonska kanaler. Pink, RTS, HRT, FTV, BHT, Arena Sport, Nova S, Hayat — alla i HD/4K. Sverigeoptimerade servrar.",
    wa: "Hej! Jag vill ha ExYu kanaler i Sverige (Pink, RTS, Arena Sport).",
    keywords: [
      ["exyu IPTV Sverige", "1 400/mån"],
      ["balkanska kanaler", "980/mån"],
      ["Pink TV Sverige", "720/mån"],
      ["Arena Sport Sverige", "590/mån"],
      ["bosanska TV Sverige", "480/mån"],
      ["srpski kanali Švedska", "420/mån"],
      ["hrvatska TV Švedska", "380/mån"],
      ["RTS Sverige", "350/mån"],
      ["HRT live", "310/mån"],
      ["Nova S online", "290/mån"],
    ],
    channels: [
      { n: "Pink 1", c: "🎬" }, { n: "Pink 2", c: "🎬" }, { n: "Pink 3", c: "🎬" },
      { n: "Pink Plus", c: "🎬" }, { n: "Pink Family", c: "🎬" },
      { n: "RTS 1 Srbija", c: "🎬" }, { n: "RTS 2", c: "🎬" }, { n: "RTS Svet", c: "🎬" },
      { n: "HRT 1 Hrvatska", c: "🎬" }, { n: "HRT 2", c: "🎬" }, { n: "HRT 3", c: "🎬" },
      { n: "HRT 4", c: "🎬" },
      { n: "FTV BiH", c: "🎬" }, { n: "BHT1", c: "📰" }, { n: "Hayat TV", c: "🎬" },
      { n: "Hayat Plus", c: "🎬" },
      { n: "Arena Sport 1 HD", c: "⚽" }, { n: "Arena Sport 2 HD", c: "⚽" },
      { n: "Arena Sport 3 HD", c: "⚽" }, { n: "Arena Sport 4 HD", c: "⚽" },
      { n: "Arena Sport 5 HD", c: "⚽" }, { n: "Arena Premium 1", c: "⚽" },
      { n: "Prva TV", c: "🎬" }, { n: "Nova S Srbija", c: "🎬" },
      { n: "Nova HR", c: "🎬" }, { n: "Doma TV", c: "🎬" },
      { n: "RTL Croatia", c: "🎬" }, { n: "RTL 2 Croatia", c: "🎬" },
      { n: "OBN Bosnia", c: "🎬" }, { n: "Alfa TV BiH", c: "🎬" },
      { n: "N1 Balkan", c: "📰" }, { n: "N1 Srbija", c: "📰" },
      { n: "N1 Hrvatska", c: "📰" }, { n: "Al Jazeera Balkans", c: "📰" },
      { n: "TV Pink BH", c: "🎬" }, { n: "Pink M Crna Gora", c: "🎬" },
      { n: "RTCG", c: "🎬" }, { n: "TV Vijesti", c: "📰" },
      { n: "MTV 1 Makedonija", c: "🎬" }, { n: "Sitel", c: "🎬" },
      { n: "TV24 Makedonija", c: "🎬" }, { n: "Kanal 5 MK", c: "🎬" },
      { n: "Sport Klub 1", c: "⚽" }, { n: "Sport Klub 2", c: "⚽" },
      { n: "Sport Klub 3", c: "⚽" }, { n: "Sport Klub 4", c: "⚽" },
      { n: "Eurosport Balkan", c: "⚽" }, { n: "Cinemania", c: "🎬" },
      { n: "Pink Hits", c: "🎵" }, { n: "Pink Folk", c: "🎵" },
      { n: "Grand TV", c: "🎵" }, { n: "Balkanika Music", c: "🎵" },
    ],
  },
  {
    slug: "arabisk",
    flag: "🇸🇦",
    name: "عربي",
    sub: "MBC, Al Jazeera, beIN Sports",
    desc: "Komplett arabiskt kanalpaket — MBC, Al Jazeera, beIN Sports 4K, OSN, Rotana, LBC, Dubai TV och 200+ kanaler från hela arabvärlden. Stabil 4K-streaming i Sverige.",
    wa: "Hej! Jag vill ha arabiska kanaler i Sverige (MBC, beIN Sports).",
    keywords: [
      ["arabisk IPTV Sverige", "1 200/mån"],
      ["MBC Sverige", "890/mån"],
      ["beIN Sports Sverige", "720/mån"],
      ["arabiska kanaler", "650/mån"],
      ["Al Jazeera Sverige", "480/mån"],
      ["OSN Sverige", "320/mån"],
      ["Rotana Cinema", "280/mån"],
      ["قنوات عربية السويد", "240/mån"],
    ],
    channels: [
      { n: "MBC 1", c: "🎬" }, { n: "MBC 2", c: "🎬" }, { n: "MBC 3", c: "👶" },
      { n: "MBC 4", c: "🎬" }, { n: "MBC Drama", c: "📺" }, { n: "MBC Action", c: "💥" },
      { n: "MBC Max", c: "🎬" }, { n: "MBC Bollywood", c: "🎬" },
      { n: "Al Jazeera", c: "📰" }, { n: "Al Arabiya", c: "📰" }, { n: "Sky News Arabia", c: "📰" },
      { n: "BBC Arabic", c: "📰" }, { n: "France 24 عربي", c: "📰" },
      { n: "beIN Sports 1 4K", c: "⚽" }, { n: "beIN Sports 2", c: "⚽" },
      { n: "beIN Sports 3", c: "⚽" }, { n: "beIN Sports 4", c: "⚽" },
      { n: "beIN Sports MAX", c: "⚽" }, { n: "beIN Sports News", c: "⚽" },
      { n: "OSN Sports", c: "⚽" }, { n: "OSN Movies", c: "🎬" },
      { n: "Rotana Cinema", c: "🎬" }, { n: "Rotana Drama", c: "📺" },
      { n: "Rotana Khalijia", c: "🎬" }, { n: "Rotana Music", c: "🎵" },
      { n: "Dubai TV", c: "🎬" }, { n: "Dubai Sports", c: "⚽" },
      { n: "Abu Dhabi TV", c: "📰" }, { n: "Abu Dhabi Sports", c: "⚽" },
      { n: "Saudi 1", c: "🎬" }, { n: "Saudi Sports", c: "⚽" },
      { n: "LBC Lebanon", c: "🎬" }, { n: "LDC Lebanon", c: "🎬" },
      { n: "MTV Lebanon", c: "🎵" }, { n: "Future TV", c: "🎬" },
      { n: "Nile Drama", c: "📺" }, { n: "ON E", c: "🎬" },
      { n: "DMC", c: "🎬" }, { n: "Al Hayat", c: "🎬" },
    ],
  },
  {
    slug: "turkisk",
    flag: "🇹🇷",
    name: "Türkçe",
    sub: "TRT, Show TV, Kanal D, beIN Sports",
    desc: "Alla turkiska favoritkanaler — TRT, Show TV, Kanal D, ATV, FOX Türkiye, Star TV. Türk dizileri, sport, nyheter och underhållning. beIN Sports TR ingår.",
    wa: "Hej! Jag vill ha turkiska kanaler i Sverige (TRT, Show TV).",
    keywords: [
      ["turkisk IPTV Sverige", "980/mån"],
      ["turkiska kanaler", "740/mån"],
      ["TRT Sverige", "520/mån"],
      ["türk dizi Sverige", "480/mån"],
      ["Show TV Sverige", "390/mån"],
      ["Kanal D Sverige", "340/mån"],
      ["beIN Sports TR", "280/mån"],
      ["İsveç türk TV", "240/mån"],
    ],
    channels: [
      { n: "TRT 1", c: "🎬" }, { n: "TRT 2", c: "🎭" }, { n: "TRT Haber", c: "📰" },
      { n: "TRT Spor", c: "⚽" }, { n: "TRT Çocuk", c: "👶" }, { n: "TRT World", c: "📰" },
      { n: "TRT Müzik", c: "🎵" }, { n: "TRT Avaz", c: "🎬" },
      { n: "Show TV", c: "🎬" }, { n: "Show Türk", c: "🎬" },
      { n: "Kanal D", c: "🎬" }, { n: "Kanal D Smart", c: "🎬" },
      { n: "Star TV", c: "🎬" }, { n: "ATV", c: "🎬" }, { n: "ATV Avrupa", c: "🎬" },
      { n: "FOX Türkiye", c: "🎬" }, { n: "TV8", c: "🎬" }, { n: "TV8.5", c: "🎬" },
      { n: "Teve 2", c: "🎬" }, { n: "Kanal 7", c: "🎬" },
      { n: "Habertürk", c: "📰" }, { n: "CNN Türk", c: "📰" }, { n: "NTV", c: "📰" },
      { n: "Bloomberg HT", c: "📰" }, { n: "TGRT Haber", c: "📰" },
      { n: "beIN Sports TR 1", c: "⚽" }, { n: "beIN Sports TR 2", c: "⚽" },
      { n: "beIN Sports TR 3", c: "⚽" }, { n: "beIN Sports TR 4", c: "⚽" },
      { n: "A Spor", c: "⚽" }, { n: "S Sport", c: "⚽" },
      { n: "Smart Spor", c: "⚽" }, { n: "Eurosport TR", c: "⚽" },
    ],
  },

  // ============ TIER 2: SECONDARY MARKETS ============
  {
    slug: "somalisk",
    flag: "🇸🇴",
    name: "Soomaali",
    sub: "Universal TV, Horn Cable, SBC",
    desc: "Somaliska kanaler — Universal TV, Horn Cable TV, SBC, Goobjoog, Mustaqbal. Stort utbud för somaliska familjer i Sverige.",
    wa: "Hej! Jag vill ha somaliska kanaler i Sverige.",
    keywords: [
      ["somalisk IPTV Sverige", "340/mån"],
      ["Universal TV Sverige", "280/mån"],
      ["somaliska kanaler", "210/mån"],
      ["Horn Cable Sverige", "150/mån"],
    ],
    channels: [
      { n: "Universal TV", c: "🎬" }, { n: "Horn Cable TV", c: "📰" },
      { n: "SBC Somalia", c: "🎬" }, { n: "Goobjoog TV", c: "📰" },
      { n: "Mustaqbal TV", c: "🎬" }, { n: "Astaan TV", c: "🎬" },
      { n: "Bulsho TV", c: "🎬" }, { n: "Eastern TV", c: "🎬" },
      { n: "VOA Somali", c: "📰" }, { n: "BBC Somali", c: "📰" },
      { n: "Somali Channel", c: "🎬" }, { n: "Royal TV Somalia", c: "🎬" },
    ],
  },
  {
    slug: "persisk",
    flag: "🇮🇷",
    name: "فارسی",
    sub: "Manoto, GEM TV, Iran International",
    desc: "Iranska och farsi-talande kanaler — Manoto, GEM TV, Iran International, BBC Persian, VOA Persian, Farsi1.",
    wa: "Hej! Jag vill ha persiska kanaler i Sverige.",
    keywords: [
      ["persisk IPTV Sverige", "420/mån"],
      ["Manoto Sverige", "350/mån"],
      ["GEM TV Sverige", "290/mån"],
      ["Iran International Sverige", "230/mån"],
    ],
    channels: [
      { n: "Manoto TV", c: "🎬" }, { n: "Manoto Plus", c: "🎬" },
      { n: "GEM TV", c: "🎬" }, { n: "GEM Music", c: "🎵" },
      { n: "GEM Drama", c: "📺" }, { n: "GEM Bollywood", c: "🎬" },
      { n: "VOA Persian", c: "📰" }, { n: "Iran International", c: "📰" },
      { n: "BBC Persian", c: "📰" }, { n: "Farsi1", c: "🎬" },
      { n: "Varzesh TV", c: "⚽" }, { n: "PMC Music", c: "🎵" },
    ],
  },
  {
    slug: "kurdisk",
    flag: "🏳️",
    name: "Kurdî",
    sub: "Rudaw, Kurdistan 24, NRT, K24",
    desc: "Kurdiska TV-kanaler — Rudaw, Kurdistan 24, NRT, K24, KTV, Zagros TV. Sorani och Kurmanji.",
    wa: "Hej! Jag vill ha kurdiska kanaler i Sverige.",
    keywords: [
      ["kurdisk IPTV Sverige", "380/mån"],
      ["Rudaw Sverige", "290/mån"],
      ["Kurdistan 24 Sverige", "240/mån"],
      ["kurdiska kanaler", "180/mån"],
    ],
    channels: [
      { n: "Rudaw", c: "📰" }, { n: "Kurdistan 24", c: "📰" },
      { n: "NRT TV", c: "🎬" }, { n: "K24", c: "📰" },
      { n: "KTV Kurdistan", c: "🎬" }, { n: "Zagros TV", c: "🎬" },
      { n: "Kurd1", c: "🎬" }, { n: "Sterk TV", c: "🎬" },
      { n: "Newroz TV", c: "🎬" }, { n: "Çira TV", c: "🎬" },
      { n: "Med TV", c: "🎬" }, { n: "GK Kurdistan", c: "🎵" },
    ],
  },
  {
    slug: "polsk",
    flag: "🇵🇱",
    name: "Polski",
    sub: "TVP, Polsat, TVN, Canal+",
    desc: "Polska TV-kanaler — TVP, Polsat, TVN, Canal+, sport, film, nyheter och rozrywka.",
    wa: "Hej! Jag vill ha polska kanaler i Sverige.",
    keywords: [
      ["polska IPTV Sverige", "310/mån"],
      ["polska kanaler", "260/mån"],
      ["TVP Sverige", "200/mån"],
      ["Polsat Szwecja", "160/mån"],
    ],
    channels: [
      { n: "TVP 1", c: "🎬" }, { n: "TVP 2", c: "🎬" }, { n: "TVP 3", c: "📰" },
      { n: "TVP Info", c: "📰" }, { n: "TVP Sport", c: "⚽" }, { n: "TVP Polonia", c: "🎬" },
      { n: "Polsat", c: "🎬" }, { n: "Polsat 2", c: "🎬" }, { n: "Polsat Sport", c: "⚽" },
      { n: "Polsat News", c: "📰" }, { n: "Polsat Film", c: "🎬" },
      { n: "TVN", c: "🎬" }, { n: "TVN 24", c: "📰" }, { n: "TVN 7", c: "🎬" },
      { n: "TVN Style", c: "🎬" }, { n: "TVN Turbo", c: "🎬" },
      { n: "Canal+ Sport PL", c: "⚽" }, { n: "Canal+ Premium", c: "🎬" },
      { n: "Canal+ Film", c: "🎬" }, { n: "Eleven Sports PL", c: "⚽" },
    ],
  },
  {
    slug: "finsk",
    flag: "🇫🇮",
    name: "Suomi",
    sub: "Yle, MTV3, Nelonen, Sub",
    desc: "Finska TV-kanaler — Yle, MTV3, Nelonen, Sub, Liv, Hero, Frii. Hela det finska utbudet.",
    wa: "Hej! Jag vill ha finska kanaler i Sverige.",
    keywords: [
      ["finsk IPTV Sverige", "280/mån"],
      ["finska kanaler", "220/mån"],
      ["Yle Sverige", "180/mån"],
      ["MTV3 Sverige", "140/mån"],
    ],
    channels: [
      { n: "Yle TV1", c: "🎬" }, { n: "Yle TV2", c: "🎬" },
      { n: "Yle Teema & Fem", c: "🎬" }, { n: "Yle Areena", c: "🎬" },
      { n: "MTV3", c: "🎬" }, { n: "MTV Sub", c: "🎬" },
      { n: "Nelonen", c: "🎬" }, { n: "Sub", c: "🎬" },
      { n: "Liv", c: "🎬" }, { n: "Hero", c: "🎬" }, { n: "Frii", c: "🎬" },
      { n: "C More Sport FI", c: "⚽" }, { n: "Viaplay Sport FI", c: "⚽" },
    ],
  },

  // ============ TIER 3: LONG-TAIL MARKETS ============
  {
    slug: "indisk",
    flag: "🇮🇳",
    name: "हिंदी",
    sub: "Star Plus, Zee TV, Sony, Colors",
    desc: "Indiska kanaler — Star Plus, Zee TV, Sony, Colors och Bollywood-filmer.",
    wa: "Hej! Jag vill ha indiska kanaler i Sverige.",
    keywords: [
      ["indisk IPTV Sverige", "320/mån"],
      ["Star Plus Sverige", "280/mån"],
      ["hindi TV Sverige", "210/mån"],
      ["Bollywood Sverige", "180/mån"],
    ],
    channels: [
      { n: "Star Plus HD", c: "🎬" }, { n: "Zee TV HD", c: "🎬" },
      { n: "Sony Entertainment", c: "🎬" }, { n: "Colors TV", c: "🎬" },
      { n: "Star Sports 1", c: "⚽" }, { n: "Aaj Tak", c: "📰" },
      { n: "Zee Cinema", c: "🎬" }, { n: "Star Gold", c: "🎬" },
      { n: "Sony Max", c: "🎬" }, { n: "Sun TV", c: "🎬" },
    ],
  },
  {
    slug: "afrikansk",
    flag: "🌍",
    name: "Afrique",
    sub: "Canal+, RTS, TFM, Nollywood",
    desc: "Afrikanska kanaler — Canal+ Afrique, RTS Sénégal, TFM, AFROTV, Nollywood TV.",
    wa: "Hej! Jag vill ha afrikanska kanaler i Sverige.",
    keywords: [
      ["afrikansk IPTV Sverige", "260/mån"],
      ["Canal+ Africa Sverige", "190/mån"],
      ["afrikanska kanaler", "170/mån"],
    ],
    channels: [
      { n: "Canal+ Afrique", c: "🎬" }, { n: "RTS 1 Sénégal", c: "🎬" },
      { n: "TFM Sénégal", c: "🎬" }, { n: "AFROTV", c: "🎬" },
      { n: "NTA Nigeria", c: "📰" }, { n: "Africa 24", c: "📰" },
      { n: "Nollywood TV", c: "🎬" }, { n: "SuperSport Africa", c: "⚽" },
    ],
  },
  {
    slug: "kinesisk",
    flag: "🇨🇳",
    name: "中文",
    sub: "CCTV, Phoenix, TVB",
    desc: "Kinesiska kanaler — CCTV, Phoenix, TVB, mandarin och kantonesiska.",
    wa: "Hej! Jag vill ha kinesiska kanaler i Sverige.",
    keywords: [
      ["kinesisk IPTV Sverige", "240/mån"],
      ["CCTV Sverige", "190/mån"],
      ["Phoenix TV Sverige", "160/mån"],
    ],
    channels: [
      { n: "CCTV 1", c: "🎬" }, { n: "CCTV 4 Int", c: "🎬" },
      { n: "Phoenix InfoNews", c: "📰" }, { n: "Phoenix Chinese", c: "🎬" },
      { n: "TVB Jade", c: "🎬" }, { n: "CCTV Sport", c: "⚽" },
    ],
  },
  {
    slug: "spansk",
    flag: "🇪🇸",
    name: "Español",
    sub: "TVE, Antena 3, Univision, LaLiga",
    desc: "Spanska kanaler — TVE, Antena 3, Univision, LaLiga, Telecinco.",
    wa: "Hej! Jag vill ha spanska kanaler i Sverige.",
    keywords: [
      ["spansk IPTV Sverige", "190/mån"],
      ["TVE Sverige", "160/mån"],
      ["Antena 3 Sverige", "130/mån"],
      ["LaLiga Sverige", "240/mån"],
    ],
    channels: [
      { n: "TVE 1", c: "🎬" }, { n: "TVE 2", c: "🎬" },
      { n: "Antena 3", c: "🎬" }, { n: "Telecinco", c: "🎬" },
      { n: "Univision", c: "🌎" }, { n: "Canal+ LaLiga", c: "⚽" },
      { n: "ESPN Latin", c: "⚽" }, { n: "DAZN España", c: "⚽" },
    ],
  },
  {
    slug: "grekisk",
    flag: "🇬🇷",
    name: "Ελληνικά",
    sub: "ERT, MEGA, ANT1, Nova Sports",
    desc: "Grekiska kanaler — ERT, MEGA, ANT1, Nova Sports, SKAI.",
    wa: "Hej! Jag vill ha grekiska kanaler i Sverige.",
    keywords: [
      ["grekisk IPTV Sverige", "180/mån"],
      ["ERT Sverige", "150/mån"],
      ["MEGA TV Sverige", "120/mån"],
    ],
    channels: [
      { n: "ERT 1", c: "🎬" }, { n: "ERT 2", c: "🎬" },
      { n: "MEGA Channel", c: "🎬" }, { n: "ANT1", c: "🎬" },
      { n: "Star GR", c: "🎬" }, { n: "SKAI TV", c: "📰" },
      { n: "Open TV", c: "🎬" }, { n: "Nova Sports GR", c: "⚽" },
    ],
  },
  {
    slug: "portugisisk",
    flag: "🇵🇹",
    name: "Português",
    sub: "RTP, SIC, TVI, Globo",
    desc: "Portugisiska och brasilianska kanaler — RTP, SIC, TVI, Globo Brasil, SporTV.",
    wa: "Hej! Jag vill ha portugisiska kanaler i Sverige.",
    keywords: [
      ["portugisisk IPTV Sverige", "160/mån"],
      ["RTP Sverige", "130/mån"],
      ["brasiliansk TV Sverige", "110/mån"],
      ["Globo Sverige", "180/mån"],
    ],
    channels: [
      { n: "RTP 1", c: "🎬" }, { n: "RTP Internacional", c: "🎬" },
      { n: "SIC Portugal", c: "🎬" }, { n: "SIC Notícias", c: "📰" },
      { n: "TVI Portugal", c: "🎬" }, { n: "Globo Brasil", c: "🎬" },
      { n: "SporTV", c: "⚽" }, { n: "Benfica TV", c: "⚽" },
    ],
  },
  {
    slug: "thai",
    flag: "🇹🇭",
    name: "ภาษาไทย",
    sub: "Thai PBS, ONE31, GMM25",
    desc: "Thailändska kanaler — Thai PBS, ONE31, GMM25, CH3.",
    wa: "Hej! Jag vill ha thailändska kanaler i Sverige.",
    keywords: [
      ["thai IPTV Sverige", "140/mån"],
      ["thailändska kanaler", "110/mån"],
    ],
    channels: [
      { n: "Thai PBS", c: "🎬" }, { n: "ONE31", c: "🎬" },
      { n: "GMM25", c: "🎬" }, { n: "CH3 Thailand", c: "🎬" },
      { n: "True Sport", c: "⚽" }, { n: "Workpoint TV", c: "🎬" },
    ],
  },
  {
    slug: "vietnamesisk",
    flag: "🇻🇳",
    name: "Tiếng Việt",
    sub: "VTV, HTV, SCTV",
    desc: "Vietnamesiska kanaler — VTV, HTV, SCTV.",
    wa: "Hej! Jag vill ha vietnamesiska kanaler i Sverige.",
    keywords: [
      ["vietnamesisk IPTV Sverige", "130/mån"],
      ["VTV Sverige", "100/mån"],
    ],
    channels: [
      { n: "VTV1", c: "🎬" }, { n: "VTV3", c: "🎬" },
      { n: "HTV7", c: "🎬" }, { n: "HTV9", c: "🎬" }, { n: "SCTV", c: "🎬" },
    ],
  },
];
