// components/shared/dict.ts
// Trilingual dictionary — Swedish (primary), English, French
// All copy is server-renderable for SEO indexing

import type { Locale, Copy } from "./types";
import { SITE } from "./site";
import { DEVICE_LIST } from "./plans";

export const dict: Record<Locale, Copy> = {
  sv: {
    brand: SITE.brand,
    top: {
      status: "Systemstatus: Online • Support svarar direkt via WhatsApp",
      urgency: "🎁 Lanseringspris garanterat — Testa gratis 24h utan kort",
    },
    nav: {
      offers: "Paket", channels: "Kanaler", faq: "FAQ", setup: "Installation",
      whatsapp: "WhatsApp", install: "Installera App", cities: "Städer", devices: "Enheter",
    },
    hero: {
      pill: "Sveriges ledande IPTV • 4K Nordic CDN • 20 000+ kanaler",
      titleA: "Bästa IPTV Sverige 2026.",
      titleB: "Direkt på din skärm.",
      lead: "Sveriges mest stabila IPTV-tjänst med SVT, TV4, Allsvenskan, SHL och 20 000+ kanaler i 4K UHD. Perfekt för svenska, arabiska, turkiska, ExYu, persiska och kurdiska tittare. Aktivering på 10 minuter via WhatsApp. Ingen bindning.",
      ctaPrices: "Se priser från 83 kr/mån",
      ctaAdvisor: "Prata med en rådgivare på svenska",
      trust: "★ 4,9/5 av 1 200+ tittare • Servrar i Sverige • Ingen bindning • Svensk support",
    },
    trial: {
      badge: "Gratis test 24h",
      title: "Testa Sveriges bästa IPTV gratis i 24 timmar",
      sub: "Inget kreditkort krävs. Kontakta oss på WhatsApp och testa hela kanalutbudet — SVT, TV4, sport, internationella kanaler — direkt på din Firestick, Smart TV, Android eller iPhone.",
      cta: "Begär gratis test nu",
      note: "Ingen bindningstid. Inget automatiskt köp. Ingen kreditkortsuppgift krävs.",
    },
    offers: {
      title: "Välj ditt IPTV-paket — från 83 kr/mån",
      sub: "Alla paket inkluderar 20 000+ kanaler, VOD, EPG och WhatsApp-support på svenska. Ingen bindning. Beställ direkt via WhatsApp.",
      order: "Beställ via WhatsApp",
      billedOnce: "Debiteras",
      perMonth: "/mån",
      save: "SPARA",
      bestSeller: "BÄSTSÄLJARE",
      totalLabel: "engångskostnad",
    },
    planNames: { p1: "1 Månad", p3: "3 Månader", p6: "6 Månader", p12: "12 Månader" },
    planPerks: {
      p1: ["20 000+ live-kanaler", "4K/UHD kvalitet", "EPG kanalguide ingår", "WhatsApp-support på svenska", "Ingen bindningstid"],
      p3: ["Populäraste valet", "20 000+ live-kanaler", "100 000+ filmer & serier", "Prioriterad support", "Guidad installation"],
      p6: ["Mycket prisvärd", "20 000+ live-kanaler", "Multi-enhet stöd", "EPG + Catch-up TV 7 dagar", "Alla kanaler ingår"],
      p12: ["Bästa värdet — endast 50 kr/mån", "Premium VIP-åtkomst", "20 000+ kanaler i 4K", "VIP-support 24/7", "Gratis uppgradering"],
    },
    channels: { title: "Utforska 20 000+ kanaler i Sverige", sub: "Välj region och se vad som ingår — svenska, nordiska, sport, internationella", more: "…och 20 000+ kanaler till" },
    devices: {
      title: "Fungerar på alla dina enheter",
      sub: "Installera på upp till 3 enheter. Vi guidar dig igenom installationen via WhatsApp på svenska — oavsett enhet.",
      list: DEVICE_LIST,
    },
    vod: {
      title: "100 000+ filmer & serier on demand",
      sub: "Nytt innehåll läggs till varje vecka. Titta när du vill, på valfri enhet.",
      stats: [
        { value: "100 000+", label: "Filmer & serier" },
        { value: "20 000+", label: "Live-kanaler" },
        { value: "4K/UHD", label: "Maximal kvalitet" },
        { value: "< 10 min", label: "Aktiveringstid" },
      ],
    },
    compare: {
      title: "Varför välja Sverige TV framför Viaplay & C More?",
      sub: "Jämförelse med traditionella streamingtjänster i Sverige 2026",
      headers: ["Tjänst", "Pris/mån", "Live-kanaler", "VOD", "4K", "Support"],
      rows: [
        { service: "Viaplay Total", price: "329 kr", live: "~150", vod: true, hd4k: true, support: "Chat" },
        { service: "C More Everything", price: "279 kr", live: "~80", vod: true, hd4k: false, support: "Chat" },
        { service: "Netflix Standard", price: "179 kr", live: "0", vod: true, hd4k: true, support: "Chat" },
        { service: "Sverige TV", price: "från 50 kr", live: "20 000+", vod: true, hd4k: true, support: "WhatsApp direkt", highlight: true },
      ],
    },
    reviews: {
      title: "Vad våra svenska kunder säger",
      sub: "Verifierade omdömen från kunder i Sverige",
      items: [
        { name: "Erik L.", city: "Stockholm", stars: 5, plan: "3 månader", text: "Installationen gick på 10 minuter med hjälp från support. SVT, TV4 och alla sportkanaler fungerar perfekt. Sparar 250 kr i månaden jämfört med Viaplay." },
        { name: "Fatima A.", city: "Göteborg", stars: 5, plan: "6 månader", text: "Äntligen borta från dyra abonnemang. Alla svenska kanaler finns, plus arabiska kanaler för familjen. Utmärkt kvalitet och snabb support." },
        { name: "Mohammed K.", city: "Malmö", stars: 5, plan: "12 månader", text: "TiviMate fungerade direkt. 4K-kvalitet på Firestick utan buffring. Bästa IPTV-tjänsten jag provat på 3 år." },
        { name: "Anna B.", city: "Uppsala", stars: 4, plan: "3 månader", text: "Lite osäker i början men supportteamet var professionellt och hjälpte mig igenom installationen steg för steg. Väldigt nöjd." },
        { name: "Lars P.", city: "Västerås", stars: 5, plan: "12 månader", text: "Testade gratis i 24 timmar och köpte direkt årsabonnemanget. Allsvenskan, Premier League och NHL — allt på ett ställe." },
        { name: "Sofia N.", city: "Stockholm", stars: 5, plan: "6 månader", text: "Fungerar perfekt på min Samsung Smart TV och min iPhone. Barn-kanalerna är ett extra plus för familjen." },
        { name: "Dragan P.", city: "Malmö", stars: 5, plan: "12 månader", text: "Konačno sve ExYu kanale na jednom mestu! Pink, RTS, HRT, Arena Sport — sve radi savršeno u 4K. Najbolji IPTV u Švedskoj." },
        { name: "Mehmet Y.", city: "Stockholm", stars: 5, plan: "6 månader", text: "TRT, Show TV, Kanal D — hepsi mükemmel çalışıyor. İsveç'te yaşayan Türkler için en iyi seçim." },
      ],
    },
    trust: {
      title: "Trygg och enkel handel",
      items: [
        { icon: "🧪", title: "Gratis test 24h", desc: "Prova utan kreditkort. Ingen risk." },
        { icon: "⚡", title: "Aktivering < 10 min", desc: "Vi aktiverar direkt via WhatsApp." },
        { icon: "💬", title: "Svensk WhatsApp-support", desc: "Svarar direkt alla dagar." },
        { icon: "🛡️", title: "Nöjd-kund-garanti", desc: "Hör av dig inom 24h om du inte är nöjd." },
        { icon: "📺", title: "4K på alla paket", desc: "Ingen extraavgift för kvalitet." },
        { icon: "🌐", title: "Optimerat för Sverige", desc: "Fungerar med Telia, Bahnhof, Com Hem." },
      ],
    },
    faq: {
      title: "Vanliga frågor om IPTV i Sverige",
      items: [
        { q: "Vad är bästa IPTV i Sverige 2026?", a: "Sverige TV är en av Sveriges ledande IPTV-tjänster 2026 med 20 000+ kanaler, 4K UHD-kvalitet, svensk WhatsApp-support och servrar i Norden för minimal buffring. Vi rankas högt för stabil streaming, prisvärt utbud (från 50 kr/månad i årspaket) och 24-timmars gratis testperiod utan kreditkort." },
        { q: "Kan jag titta på SVT, TV4 och svenska kanaler?", a: "Ja, alla stora svenska kanaler ingår: SVT1 HD, SVT2 HD, TV4 HD, Kanal 5, TV3, TV6, TV8, Sjuan, Kanal 9, SVT Play Live, regionala SVT-kanaler och fler — alla i HD-kvalitet, många i 4K." },
        { q: "Är IPTV lagligt i Sverige?", a: "Att titta på IPTV är lagligt i Sverige så länge du inte sprider innehåll vidare. Vår tjänst använder licensierad infrastruktur och vi följer EU:s regelverk för konsumentskydd." },
        { q: "Fungerar det med TiviMate och IPTV Smarters?", a: "Ja. Vi stöder TiviMate, IPTV Smarters Pro, GSE Smart IPTV, Smart IPTV, XCIPTV, Kodi och alla vanliga M3U-appar. Vi skickar M3U-länken och Xtream Codes direkt via WhatsApp." },
        { q: "Vilka enheter stöds?", a: "Firestick (alla modeller), Smart TV (Samsung, LG, Sony, Philips), Android, iPhone, iPad, Android TV Box, MAG Box, Apple TV och PC/Mac. Vi guidar dig igenom installationen på din specifika enhet via WhatsApp." },
        { q: "Hur snabbt aktiveras tjänsten?", a: "Vanligtvis inom 5–10 minuter efter beställning via WhatsApp, även på helger. För MAG Box-aktivering tar det max 15 minuter under kontorstid." },
        { q: "Ingår EPG (kanalguide) på svenska?", a: "Ja. En fullständig elektronisk kanalguide (EPG) på svenska ingår i alla paket, så du alltid ser vad som visas och vad som kommer. Vi uppdaterar EPG dagligen." },
        { q: "Kan jag titta på flera skärmar samtidigt?", a: "Standardpaketet inkluderar 1 anslutning. Vi har multi-skärm-paket (2, 3 eller 4 anslutningar) för hela hushåll. Kontakta oss på WhatsApp för pris." },
        { q: "Behöver jag VPN för att titta i Sverige?", a: "Nej, ingen VPN behövs i Sverige. Vår tjänst fungerar direkt med svenska internetleverantörer (Telia, Bahnhof, Com Hem, Tele2). VPN rekommenderas endast utomlands för stabilare anslutning." },
        { q: "Fungerar tjänsten utomlands?", a: "Ja, tjänsten fungerar i 50+ länder. Perfekt för svenskar i Dubai, USA, UK, Tyskland, Spanien — du kan se SVT, TV4, Allsvenskan och SHL var du än är. Vi rekommenderar VPN utomlands för bästa stabilitet." },
        { q: "Hur betalar jag — Swish, BankID, Klarna?", a: "Vi accepterar Swish, BankID, MobilePay, Klarna, PayPal, Apple Pay, Google Pay, Visa, Mastercard, Wise, Revolut och Bitcoin. Allt sker säkert via WhatsApp. Inga dolda avgifter." },
        { q: "Vad händer om tjänsten slutar fungera?", a: "Kontakta oss direkt på WhatsApp. Vi löser tekniska problem vanligtvis inom 1–2 timmar med svensk support. Ingen kund lämnas utan hjälp. Vi har 99,9% uptime som standard." },
        { q: "Kan jag se Allsvenskan, SHL och svensk sport?", a: "Ja! Svenska sportkanaler ingår — du kan följa Allsvenskan, SHL, Damallsvenskan, Svenska Cupen, Handbollsligan, plus internationell sport som Premier League, La Liga, Champions League, NHL, NBA, NFL och Formel 1." },
        { q: "Har ni kanaler för ExYu, arabiska, turkiska eller persiska familjer?", a: "Ja! Vi har dedikerade paket för ExYu (Pink, RTS, HRT, Arena Sport), arabiska (MBC, Al Jazeera, beIN Sports), turkiska (TRT, Show TV, Kanal D), persiska (Manoto, GEM TV), kurdiska, somaliska, polska, finska och 15+ andra språk. Se vår 'TV-länder'-sektion." },
        { q: "Kan jag avbryta abonnemanget när jag vill?", a: "Det finns ingen bindningstid. Du betalar en gång och tjänsten löper ut automatiskt efter vald period (1, 3, 6 eller 12 månader). Inga uppsägningsavgifter, inga dolda kostnader." },
        { q: "Hur snabb internet behöver jag?", a: "Minimum 10 Mbit/s för HD-streaming och 25 Mbit/s för 4K-streaming. De flesta svenska bredbandsabonnemang (Telia, Bahnhof, Com Hem fiber) klarar detta enkelt. Ethernet-kabel ger bättre stabilitet än Wi-Fi." },
      ],
    },
    cities: {
      title: "IPTV i hela Sverige — lokal anpassning",
      sub: "Sveriges bästa IPTV-tjänst — optimerat för alla hushåll i alla städer.",
      button: "Kontakta oss",
      items: [
        { name: "Stockholm", text: "Bästa IPTV Stockholm 2026 — perfekt för stockholms-hushåll som vill ersätta Viaplay eller C More med stabil och prisvärd IPTV. SVT, sport och internationella kanaler i ett paket. Optimerat för Bahnhof, Telia och Com Hem." },
        { name: "Göteborg", text: "IPTV Göteborg — optimerat för hushåll i västra Sverige. Följ IFK Göteborg och alla svenska sportsändningar (Allsvenskan, SHL), plus internationella kanaler på alla enheter. Levererat via Nordic CDN för minimal buffring." },
        { name: "Malmö", text: "IPTV Malmö — bra för malmöbor som söker arabiska, turkiska, ExYu eller internationella kanaler utöver de svenska. Vi har Sveriges största utbud av flerspråkiga kanaler. Stort persiskt och kurdiskt utbud även." },
        { name: "Uppsala", text: "IPTV Uppsala — passar studenter och familjer. Ingen bindningstid — fungerar på laptop, mobil och TV. Stabil streaming via Bahnhof och universitetets fibernät." },
        { name: "Västerås", text: "IPTV Västerås — stabil IPTV-lösning för Västerås med enkel installation via WhatsApp och full support på svenska. SVT, TV4, sport och 20 000+ internationella kanaler." },
        { name: "Linköping", text: "IPTV Linköping — för östgötar som vill ha allt på ett ställe. Allsvenskan, SHL, Premier League och svenska kanaler i 4K UHD. Snabb aktivering via WhatsApp." },
        { name: "Örebro", text: "IPTV Örebro — perfekt val för örebrohushåll. Komplett svensk TV plus 19 språk för flerspråkiga familjer i Örebro län." },
        { name: "Helsingborg", text: "IPTV Helsingborg — sydsvenskt premiumval. Svenska kanaler, danska kanaler (DR1, TV2), tyska och brittiska kanaler för helsingborgarnas internationella livsstil." },
      ],
    },
    setup: {
      title: "Snabb installation — 10 minuter på Firestick eller Smart TV",
      sub: "Fungerar på Firestick, Samsung Smart TV, LG Smart TV, iPhone, Android, MAG Box och mer. Vi guidar dig hela vägen på svenska.",
      button: "Få installationshjälp nu",
      steps: [
        { step: "1", text: "Kontakta oss på WhatsApp — berätta vilken enhet du har (Firestick, Samsung TV, etc)." },
        { step: "2", text: "Välj ditt paket och slutför betalningen via Swish, BankID eller Klarna." },
        { step: "3", text: "Få din M3U-länk och installationsguide direkt — börja titta inom 10 minuter." },
      ],
    },
    footer: {
      rights: "Alla rättigheter förbehållna.",
      note: "Optimerat för snabb och stabil streaming i hela Sverige. Servrar i Stockholm och Helsingfors.",
      legal: "Juridisk information",
      privacy: "Integritetspolicy",
      terms: "Användarvillkor",
      refund: "Nöjd-kund-policy",
    },
    whatsapp: {
      generic: "Hej! Jag behöver hjälp med Sverige TV.",
      trial: "Hej! Jag vill testa Sverige TV gratis i 24 timmar. Kan du hjälpa mig?",
      orderMessage: (p, pr, c) => `Hej! Jag vill beställa ${p} (${pr} ${c}). Kan du hjälpa mig komma igång?`,
    },
    bot: {
      greeting1: "Hej! 👋 Jag heter Moa.",
      greeting2: "Jag kan hjälpa dig med paket, gratis test eller installation. Vad undrar du?",
      price1: "Vi har paket från 50 kr/mån — 1, 3, 6 eller 12 månader. Alla inkluderar 20 000+ kanaler och EPG.",
      price2: "Vill du se paketen direkt, eller testa gratis i 24h först?",
      install1: "Firestick och Smart TV är våra populäraste enheter — installationen tar 10 minuter.",
      install2: "Jag skickar installationshjälp direkt på WhatsApp!",
      trial1: "Absolut! Vi erbjuder 24 timmars gratis test — inget kreditkort krävs.",
      trial2: "Klicka nedan så skickar jag testlänken direkt via WhatsApp.",
      default1: "Jag kan hjälpa dig med paket, gratis test, installation och kompatibilitet.",
      default2: "Snabbast hjälp får du på WhatsApp — klicka nedan!",
      quick: ["Visa priser 💰", "Gratis test 24h 🧪", "Firestick-hjälp 🔥", "Vilka kanaler? 📺"],
    },
  },

  en: {
    brand: SITE.brand,
    top: {
      status: "Status: Online • Instant WhatsApp Support",
      urgency: "🎁 Launch price guaranteed — Free 24h trial, no credit card",
    },
    nav: { offers: "Plans", channels: "Channels", faq: "FAQ", setup: "Setup", whatsapp: "WhatsApp", install: "Install App", cities: "Cities", devices: "Devices" },
    hero: {
      pill: "Sweden's leading IPTV • Nordic 4K CDN • 20,000+ channels",
      titleA: "Best IPTV Sweden 2026.",
      titleB: "Right on your screen.",
      lead: "Sweden's most stable IPTV service with SVT, TV4, Allsvenskan, SHL, and 20,000+ channels in 4K UHD. Perfect for Swedish, Arabic, Turkish, ExYu, Persian, Kurdish viewers. 10-minute activation via WhatsApp. No commitment.",
      ctaPrices: "See plans from 50 kr/month",
      ctaAdvisor: "Talk to a Swedish-speaking advisor",
      trust: "★ 4.9/5 from 1,200+ viewers • Servers in Sweden • No contract • Swedish support",
    },
    trial: {
      badge: "Free 24h trial",
      title: "Try Sweden's best IPTV free for 24 hours",
      sub: "No credit card required. Contact us on WhatsApp and test the full channel lineup — SVT, TV4, sports, international channels — directly on your Firestick, Smart TV, Android or iPhone.",
      cta: "Request free trial now",
      note: "No commitment. No automatic charge. No credit card details needed.",
    },
    offers: {
      title: "Pick your IPTV plan — from 50 kr/month",
      sub: "All plans include 20,000+ channels, VOD, EPG and Swedish WhatsApp support. No commitment. Order via WhatsApp.",
      order: "Order via WhatsApp",
      billedOnce: "Billed",
      perMonth: "/mo",
      save: "SAVE",
      bestSeller: "BEST SELLER",
      totalLabel: "one-time payment",
    },
    planNames: { p1: "1 Month", p3: "3 Months", p6: "6 Months", p12: "12 Months" },
    planPerks: {
      p1: ["20,000+ live channels", "4K/UHD quality", "EPG guide included", "Swedish WhatsApp support", "No contract"],
      p3: ["Most popular choice", "20,000+ live channels", "100,000+ movies & series", "Priority support", "Guided setup"],
      p6: ["Best value", "20,000+ live channels", "Multi-device support", "EPG + Catch-up TV 7 days", "All channels included"],
      p12: ["Ultimate value — only 50 kr/mo", "Premium VIP access", "20,000+ channels in 4K", "VIP 24/7 support", "Free upgrade"],
    },
    channels: { title: "Explore 20,000+ channels", sub: "Choose a region to preview Swedish, Nordic, sports, and international channels", more: "…and 20,000+ more" },
    devices: {
      title: "Works on all your devices",
      sub: "Install on up to 3 devices. We guide you on WhatsApp in Swedish or English — for any device.",
      list: DEVICE_LIST,
    },
    vod: {
      title: "100,000+ movies & series on demand",
      sub: "New content added weekly. Watch anytime, on any device.",
      stats: [
        { value: "100,000+", label: "Movies & series" },
        { value: "20,000+", label: "Live channels" },
        { value: "4K/UHD", label: "Max quality" },
        { value: "< 10 min", label: "Activation time" },
      ],
    },
    compare: {
      title: "Why choose Sverige TV over Viaplay & C More?",
      sub: "Comparison with traditional Swedish streaming services 2026",
      headers: ["Service", "Price/mo", "Live channels", "VOD", "4K", "Support"],
      rows: [
        { service: "Viaplay Total", price: "329 kr", live: "~150", vod: true, hd4k: true, support: "Chat" },
        { service: "C More Everything", price: "279 kr", live: "~80", vod: true, hd4k: false, support: "Chat" },
        { service: "Netflix Standard", price: "179 kr", live: "0", vod: true, hd4k: true, support: "Chat" },
        { service: "Sverige TV", price: "from 50 kr", live: "20,000+", vod: true, hd4k: true, support: "WhatsApp direct", highlight: true },
      ],
    },
    reviews: {
      title: "What our Swedish customers say",
      sub: "Verified reviews from customers in Sweden",
      items: [
        { name: "Erik L.", city: "Stockholm", stars: 5, plan: "3 months", text: "Setup took 10 minutes with support's help. SVT, TV4 and all sports channels work perfectly. Saving 250 kr/month compared to Viaplay." },
        { name: "Fatima A.", city: "Gothenburg", stars: 5, plan: "6 months", text: "Finally free from expensive subscriptions. All Swedish channels included, plus Arabic channels for the family. Excellent quality." },
        { name: "Mohammed K.", city: "Malmö", stars: 5, plan: "12 months", text: "TiviMate worked straight away. 4K quality on Firestick with zero buffering. Best IPTV service I've tried in 3 years." },
        { name: "Anna B.", city: "Uppsala", stars: 4, plan: "3 months", text: "Was a little nervous at first but the support team was professional and walked me through every step. Very happy." },
        { name: "Lars P.", city: "Västerås", stars: 5, plan: "12 months", text: "Tested free for 24 hours and immediately bought the annual plan. Allsvenskan, Premier League and NHL — all in one place." },
        { name: "Sofia N.", city: "Stockholm", stars: 5, plan: "6 months", text: "Works perfectly on my Samsung Smart TV and iPhone. The kids' channels are a great bonus for the family." },
        { name: "Dragan P.", city: "Malmö", stars: 5, plan: "12 months", text: "Finally all ExYu channels in one place! Pink, RTS, HRT, Arena Sport — everything works perfectly in 4K. Best IPTV in Sweden." },
        { name: "Mehmet Y.", city: "Stockholm", stars: 5, plan: "6 months", text: "TRT, Show TV, Kanal D — all working perfectly. Best choice for Turks living in Sweden." },
      ],
    },
    trust: {
      title: "Safe & simple",
      items: [
        { icon: "🧪", title: "Free 24h trial", desc: "Test without a credit card. Zero risk." },
        { icon: "⚡", title: "Activated in < 10 min", desc: "We activate instantly via WhatsApp." },
        { icon: "💬", title: "Swedish WhatsApp support", desc: "Fast response, every day." },
        { icon: "🛡️", title: "Satisfaction guarantee", desc: "Not happy? Contact us within 24h." },
        { icon: "📺", title: "4K on all plans", desc: "No surcharge for quality." },
        { icon: "🌐", title: "Optimized for Sweden", desc: "Works with Telia, Bahnhof, Com Hem." },
      ],
    },
    faq: {
      title: "Frequently Asked Questions about IPTV in Sweden",
      items: [
        { q: "What is the best IPTV in Sweden 2026?", a: "Sverige TV is one of Sweden's leading IPTV services in 2026 with 20,000+ channels, 4K UHD quality, Swedish WhatsApp support and Nordic servers for minimal buffering. We rank highly for stable streaming, affordable plans (from 50 kr/month annual), and 24-hour free trial without credit card." },
        { q: "Can I watch SVT, TV4 and Swedish channels?", a: "Yes, all major Swedish channels are included: SVT1 HD, SVT2 HD, TV4 HD, Kanal 5, TV3, TV6, TV8, Sjuan, Kanal 9, SVT Play Live, regional SVT channels and more — all in HD, many in 4K." },
        { q: "Is IPTV legal in Sweden?", a: "Watching IPTV is legal in Sweden as long as you don't redistribute content. Our service uses licensed infrastructure and we comply with EU consumer protection regulations." },
        { q: "Compatible with TiviMate and IPTV Smarters?", a: "Yes. We support TiviMate, IPTV Smarters Pro, GSE Smart IPTV, Smart IPTV, XCIPTV, Kodi and all standard M3U apps. We send the M3U link and Xtream Codes directly via WhatsApp." },
        { q: "Which devices are supported?", a: "Firestick (all models), Smart TV (Samsung, LG, Sony, Philips), Android, iPhone, iPad, Android TV Box, MAG Box, Apple TV and PC/Mac. We guide you through setup on your specific device via WhatsApp." },
        { q: "How quickly is the service activated?", a: "Usually within 5–10 minutes after ordering via WhatsApp, even on weekends. MAG Box activation takes max 15 minutes during office hours." },
        { q: "Is EPG (channel guide) included in Swedish?", a: "Yes. A full Electronic Programme Guide (EPG) in Swedish is included with all plans. We update EPG daily." },
        { q: "Can I watch on multiple screens at the same time?", a: "Standard plan includes 1 connection. We have multi-screen plans (2, 3 or 4 connections) for households. Contact us on WhatsApp for pricing." },
        { q: "Do I need a VPN in Sweden?", a: "No, no VPN needed in Sweden. Our service works directly with Swedish ISPs (Telia, Bahnhof, Com Hem, Tele2). VPN only recommended abroad for stability." },
        { q: "Does it work abroad?", a: "Yes, the service works in 50+ countries. Perfect for Swedes in Dubai, USA, UK, Germany, Spain — watch SVT, TV4, Allsvenskan and SHL anywhere. We recommend VPN abroad for best stability." },
        { q: "How do I pay — Swish, BankID, Klarna?", a: "We accept Swish, BankID, MobilePay, Klarna, PayPal, Apple Pay, Google Pay, Visa, Mastercard, Wise, Revolut and Bitcoin. All secure via WhatsApp. No hidden fees." },
        { q: "What if the service stops working?", a: "Contact us directly on WhatsApp. We resolve technical issues usually within 1–2 hours with Swedish support. 99.9% uptime as standard." },
        { q: "Can I watch Allsvenskan, SHL and Swedish sports?", a: "Yes! Swedish sports channels are included — Allsvenskan, SHL, Damallsvenskan, Svenska Cupen, Handbollsligan, plus international sports like Premier League, La Liga, Champions League, NHL, NBA, NFL and Formula 1." },
        { q: "Do you have channels for ExYu, Arabic, Turkish or Persian families?", a: "Yes! We have dedicated packages for ExYu (Pink, RTS, HRT, Arena Sport), Arabic (MBC, Al Jazeera, beIN Sports), Turkish (TRT, Show TV, Kanal D), Persian (Manoto, GEM TV), Kurdish, Somali, Polish, Finnish and 15+ other languages." },
        { q: "Can I cancel my subscription anytime?", a: "There's no contract. You pay once and the service expires automatically after the chosen period (1, 3, 6 or 12 months). No cancellation fees, no hidden costs." },
        { q: "How fast internet do I need?", a: "Minimum 10 Mbit/s for HD streaming and 25 Mbit/s for 4K. Most Swedish broadband plans (Telia, Bahnhof, Com Hem fiber) handle this easily. Ethernet gives better stability than Wi-Fi." },
      ],
    },
    cities: {
      title: "TV & Streaming all over Sweden",
      sub: "Optimized for Swedish households wherever you live.",
      button: "Contact us",
      items: [
        { name: "Stockholm", text: "Best IPTV Stockholm 2026 — perfect for Stockholm households looking to replace Viaplay or C More with stable, affordable IPTV. Swedish, sports and international channels in one package. Optimized for Bahnhof, Telia, Com Hem." },
        { name: "Gothenburg", text: "IPTV Gothenburg — optimized for households in western Sweden. Follow IFK Göteborg and all Swedish sports (Allsvenskan, SHL), plus international channels. Delivered via Nordic CDN for minimal buffering." },
        { name: "Malmö", text: "IPTV Malmö — great for Malmö residents seeking Arabic, Turkish, ExYu or international channels alongside Swedish content. Sweden's largest multilingual lineup." },
        { name: "Uppsala", text: "IPTV Uppsala — ideal for students and families. No contract, works on laptop, phone and TV. Stable streaming via Bahnhof and university fiber." },
        { name: "Västerås", text: "IPTV Västerås — stable IPTV for Västerås with easy WhatsApp setup and full Swedish support. SVT, TV4, sports and 20,000+ international channels." },
        { name: "Linköping", text: "IPTV Linköping — for residents who want everything in one place. Allsvenskan, SHL, Premier League and Swedish channels in 4K UHD." },
        { name: "Örebro", text: "IPTV Örebro — perfect choice for Örebro households. Complete Swedish TV plus 19 languages for multilingual families." },
        { name: "Helsingborg", text: "IPTV Helsingborg — premium choice for southern Sweden. Swedish channels, Danish channels (DR1, TV2), German and British channels for international lifestyle." },
      ],
    },
    setup: {
      title: "Quick setup — 10 minutes on Firestick or Smart TV",
      sub: "Works on Firestick, Samsung Smart TV, LG, iPhone, Android, MAG Box and more. We guide you in Swedish or English.",
      button: "Get setup help now",
      steps: [
        { step: "1", text: "Contact us on WhatsApp — tell us your device (Firestick, Samsung TV, etc)." },
        { step: "2", text: "Choose your plan and pay via Swish, BankID or Klarna." },
        { step: "3", text: "Get your M3U link and setup guide — start watching within 10 minutes." },
      ],
    },
    footer: {
      rights: "All rights reserved.",
      note: "Optimized for fast and stable streaming throughout Sweden. Servers in Stockholm and Helsinki.",
      legal: "Legal",
      privacy: "Privacy Policy",
      terms: "Terms of Use",
      refund: "Satisfaction Policy",
    },
    whatsapp: {
      generic: "Hi! I need help with Sverige TV.",
      trial: "Hi! I'd like to try Sverige TV free for 24 hours. Can you help me?",
      orderMessage: (p, pr, c) => `Hi! I want to order ${p} (${pr} ${c}). Can you help me get started?`,
    },
    bot: {
      greeting1: "Hi! 👋 I'm Moa.",
      greeting2: "I can help with plans, free trial, or setup. What would you like to know?",
      price1: "We have plans from 50 kr/month — 1, 3, 6 or 12 months. All include 20,000+ channels and EPG.",
      price2: "Want me to guide you to the right plan, or try free for 24h first?",
      install1: "Firestick and Smart TV are our most popular devices — setup takes 10 minutes.",
      install2: "I'll send you step-by-step setup instructions directly on WhatsApp!",
      trial1: "Absolutely! We offer a 24-hour free trial — no credit card needed.",
      trial2: "Click below and I'll send the trial link directly on WhatsApp.",
      default1: "I can help with plans, free trial, setup and compatibility.",
      default2: "For the fastest help — reach out on WhatsApp!",
      quick: ["See prices 💰", "Free 24h trial 🧪", "Firestick help 🔥", "Which channels? 📺"],
    },
  },

  fr: {
    brand: SITE.brand,
    top: {
      status: "Serveurs : Opérationnels • Support WhatsApp immédiat",
      urgency: "🎁 Prix de lancement garanti — Essai gratuit 24h sans carte",
    },
    nav: { offers: "Offres", channels: "Chaînes", faq: "FAQ", setup: "Installation", whatsapp: "WhatsApp", install: "Installer l'App", cities: "Villes", devices: "Appareils" },
    hero: {
      pill: "Le leader IPTV en Suède • CDN 4K nordique • 20 000+ chaînes",
      titleA: "Meilleure IPTV Suède 2026.",
      titleB: "Direct sur votre écran.",
      lead: "Le service IPTV le plus stable de Suède avec SVT, TV4, Allsvenskan, SHL et 20 000+ chaînes en 4K UHD. Parfait pour les téléspectateurs suédois, arabes, turcs, ExYu, persans et kurdes. Activation en 10 minutes via WhatsApp. Sans engagement.",
      ctaPrices: "Voir les offres dès 50 kr/mois",
      ctaAdvisor: "Parler à un conseiller en suédois",
      trust: "★ 4,9/5 sur 1 200+ utilisateurs • Serveurs en Suède • Sans engagement • Support en suédois",
    },
    trial: {
      badge: "Essai gratuit 24h",
      title: "Testez la meilleure IPTV suédoise pendant 24h",
      sub: "Aucune carte bancaire requise. Contactez-nous sur WhatsApp et testez toutes les chaînes — SVT, TV4, sport, international — directement sur votre Firestick, Smart TV, Android ou iPhone.",
      cta: "Demander l'essai gratuit",
      note: "Sans engagement. Sans achat automatique. Aucune information bancaire requise.",
    },
    offers: {
      title: "Choisissez votre offre IPTV — dès 50 kr/mois",
      sub: "Toutes les offres incluent 20 000+ chaînes, VOD, EPG et support WhatsApp en suédois. Sans engagement. Commandez via WhatsApp.",
      order: "Commander via WhatsApp",
      billedOnce: "Facturé",
      perMonth: "/mois",
      save: "ÉCO",
      bestSeller: "POPULAIRE",
      totalLabel: "paiement unique",
    },
    planNames: { p1: "1 mois", p3: "3 mois", p6: "6 mois", p12: "12 mois" },
    planPerks: {
      p1: ["20 000+ chaînes live", "Qualité 4K/UHD", "Guide EPG inclus", "Support WhatsApp suédois", "Sans engagement"],
      p3: ["Choix le plus populaire", "20 000+ chaînes live", "100 000+ films & séries", "Support prioritaire", "Installation guidée"],
      p6: ["Meilleur rapport qualité/prix", "20 000+ chaînes live", "Multi-appareils", "EPG + Catch-up TV 7 jours", "Toutes les chaînes incluses"],
      p12: ["Valeur ultime — 50 kr/mois", "Accès VIP premium", "20 000+ chaînes en 4K", "Support VIP 24/7", "Mise à jour gratuite"],
    },
    channels: { title: "Explorez 20 000+ chaînes", sub: "Choisissez une région pour voir les chaînes suédoises, nordiques, sport et internationales", more: "…et 20 000+ autres chaînes" },
    devices: {
      title: "Compatible avec tous vos appareils",
      sub: "Installez sur jusqu'à 3 appareils. Nous vous guidons via WhatsApp en suédois, anglais ou français.",
      list: DEVICE_LIST,
    },
    vod: {
      title: "100 000+ films & séries à la demande",
      sub: "Nouveau contenu chaque semaine. Regardez quand vous voulez, sur n'importe quel appareil.",
      stats: [
        { value: "100 000+", label: "Films & séries" },
        { value: "20 000+", label: "Chaînes live" },
        { value: "4K/UHD", label: "Qualité maximale" },
        { value: "< 10 min", label: "Délai d'activation" },
      ],
    },
    compare: {
      title: "Pourquoi choisir Sverige TV plutôt que Viaplay ?",
      sub: "Comparaison avec les services de streaming suédois 2026",
      headers: ["Service", "Prix/mois", "Chaînes live", "VOD", "4K", "Support"],
      rows: [
        { service: "Viaplay Total", price: "329 kr", live: "~150", vod: true, hd4k: true, support: "Chat" },
        { service: "C More Everything", price: "279 kr", live: "~80", vod: true, hd4k: false, support: "Chat" },
        { service: "Netflix Standard", price: "179 kr", live: "0", vod: true, hd4k: true, support: "Chat" },
        { service: "Sverige TV", price: "dès 50 kr", live: "20 000+", vod: true, hd4k: true, support: "WhatsApp direct", highlight: true },
      ],
    },
    reviews: {
      title: "Ce que disent nos clients",
      sub: "Avis vérifiés de clients en Suède",
      items: [
        { name: "Erik L.", city: "Stockholm", stars: 5, plan: "3 mois", text: "L'installation a pris 10 minutes avec l'aide du support. SVT, TV4 et toutes les chaînes sport fonctionnent parfaitement. J'économise 250 kr/mois vs Viaplay." },
        { name: "Fatima A.", city: "Göteborg", stars: 5, plan: "6 mois", text: "Enfin libérée des abonnements chers. Toutes les chaînes suédoises plus les chaînes arabes pour la famille. Excellente qualité." },
        { name: "Mohammed K.", city: "Malmö", stars: 5, plan: "12 mois", text: "TiviMate a fonctionné immédiatement. Qualité 4K sur Firestick sans aucun buffering. Meilleur service IPTV testé en 3 ans." },
        { name: "Anna B.", city: "Uppsala", stars: 4, plan: "3 mois", text: "Un peu hésitante au début mais l'équipe support était professionnelle et m'a guidée pas à pas. Très satisfaite." },
        { name: "Lars P.", city: "Västerås", stars: 5, plan: "12 mois", text: "Testé gratuitement 24h et immédiatement pris l'abonnement annuel. Allsvenskan, Premier League et NHL — tout au même endroit." },
        { name: "Sofia N.", city: "Stockholm", stars: 5, plan: "6 mois", text: "Fonctionne parfaitement sur mon Samsung Smart TV et mon iPhone. Les chaînes pour enfants sont un plus pour la famille." },
        { name: "Dragan P.", city: "Malmö", stars: 5, plan: "12 mois", text: "Enfin toutes les chaînes ExYu en un seul endroit ! Pink, RTS, HRT, Arena Sport — tout fonctionne en 4K. La meilleure IPTV en Suède." },
        { name: "Mehmet Y.", city: "Stockholm", stars: 5, plan: "6 mois", text: "TRT, Show TV, Kanal D — tout fonctionne parfaitement. Le meilleur choix pour les Turcs vivant en Suède." },
      ],
    },
    trust: {
      title: "Commerce sûr et simple",
      items: [
        { icon: "🧪", title: "Essai gratuit 24h", desc: "Testez sans carte bancaire. Zéro risque." },
        { icon: "⚡", title: "Activation < 10 min", desc: "Activation immédiate via WhatsApp." },
        { icon: "💬", title: "Support WhatsApp suédois", desc: "Réponse rapide, tous les jours." },
        { icon: "🛡️", title: "Garantie satisfaction", desc: "Pas satisfait ? Contactez-nous sous 24h." },
        { icon: "📺", title: "4K sur toutes les offres", desc: "Sans supplément pour la qualité." },
        { icon: "🌐", title: "Optimisé pour la Suède", desc: "Compatible avec tous les FAI suédois." },
      ],
    },
    faq: {
      title: "Questions fréquentes sur l'IPTV en Suède",
      items: [
        { q: "Quelle est la meilleure IPTV en Suède 2026 ?", a: "Sverige TV est l'un des leaders du marché IPTV suédois en 2026 avec 20 000+ chaînes, qualité 4K UHD, support WhatsApp en suédois et serveurs nordiques pour un buffering minimal. Plans dès 50 kr/mois (annuel) avec essai gratuit 24h sans carte bancaire." },
        { q: "Puis-je regarder SVT, TV4 et les chaînes suédoises ?", a: "Oui, toutes les grandes chaînes suédoises sont incluses : SVT1 HD, SVT2 HD, TV4 HD, Kanal 5, TV3, TV6, TV8, Sjuan, Kanal 9, SVT Play Live et plus — toutes en HD, beaucoup en 4K." },
        { q: "L'IPTV est-elle légale en Suède ?", a: "Regarder l'IPTV est légal en Suède tant que vous ne redistribuez pas le contenu. Notre service utilise une infrastructure licenciée et nous respectons la réglementation européenne." },
        { q: "Compatible avec TiviMate et IPTV Smarters ?", a: "Oui. Nous supportons TiviMate, IPTV Smarters Pro, GSE Smart IPTV, Smart IPTV, XCIPTV, Kodi et toutes les apps M3U standard. Lien M3U envoyé via WhatsApp." },
        { q: "Quels appareils sont supportés ?", a: "Firestick (tous modèles), Smart TV (Samsung, LG, Sony, Philips), Android, iPhone, iPad, Android TV Box, MAG Box, Apple TV et PC/Mac. Nous vous guidons pour votre appareil via WhatsApp." },
        { q: "Combien de temps prend l'activation ?", a: "5 à 10 minutes après commande via WhatsApp, même le week-end. Activation MAG Box max 15 minutes en heures de bureau." },
        { q: "Le guide EPG est-il inclus en suédois ?", a: "Oui. Guide électronique des programmes (EPG) en suédois inclus dans toutes les offres. Mise à jour quotidienne." },
        { q: "Puis-je regarder sur plusieurs écrans ?", a: "L'offre standard inclut 1 connexion. Offres multi-écrans (2, 3 ou 4 connexions) disponibles. Contactez-nous sur WhatsApp." },
        { q: "Ai-je besoin d'un VPN en Suède ?", a: "Non, pas de VPN nécessaire en Suède. Le service fonctionne directement avec les FAI suédois (Telia, Bahnhof, Com Hem). VPN recommandé seulement à l'étranger." },
        { q: "Ça fonctionne à l'étranger ?", a: "Oui, le service fonctionne dans 50+ pays. Parfait pour les Suédois à Dubaï, USA, UK, Allemagne, Espagne — regardez SVT, TV4, Allsvenskan partout. VPN recommandé à l'étranger." },
        { q: "Comment payer — Swish, BankID, Klarna ?", a: "Nous acceptons Swish, BankID, MobilePay, Klarna, PayPal, Apple Pay, Google Pay, Visa, Mastercard, Wise, Revolut et Bitcoin. Tout sécurisé via WhatsApp. Aucun frais caché." },
        { q: "Que faire si le service ne fonctionne pas ?", a: "Contactez-nous directement sur WhatsApp. Nous résolvons les problèmes techniques généralement en 1 à 2 heures avec support en suédois. 99,9% de uptime." },
        { q: "Puis-je regarder Allsvenskan, SHL et le sport suédois ?", a: "Oui ! Chaînes sport suédoises incluses — Allsvenskan, SHL, Damallsvenskan, Svenska Cupen, plus Premier League, La Liga, Champions League, NHL, NBA, NFL, F1." },
        { q: "Avez-vous des chaînes ExYu, arabes, turques ou persanes ?", a: "Oui ! Forfaits dédiés pour ExYu (Pink, RTS, HRT, Arena Sport), arabe (MBC, Al Jazeera, beIN Sports), turc (TRT, Show TV, Kanal D), persan (Manoto, GEM TV), kurde, somali, polonais, finlandais et 15+ autres langues." },
        { q: "Puis-je annuler mon abonnement ?", a: "Aucun engagement. Vous payez une fois et le service expire automatiquement après la période choisie (1, 3, 6 ou 12 mois). Sans frais d'annulation." },
        { q: "Quelle vitesse internet me faut-il ?", a: "Minimum 10 Mbit/s pour HD, 25 Mbit/s pour 4K. La plupart des abonnements suédois (Telia, Bahnhof, Com Hem fibre) le permettent. Ethernet plus stable que Wi-Fi." },
      ],
    },
    cities: {
      title: "TV partout en Suède",
      sub: "Optimisé pour les foyers suédois où que vous soyez.",
      button: "Nous contacter",
      items: [
        { name: "Stockholm", text: "Meilleure IPTV Stockholm 2026 — parfait pour les foyers stockholmois souhaitant remplacer Viaplay ou C More. Chaînes suédoises, sport et international en un abonnement. Optimisé Bahnhof, Telia, Com Hem." },
        { name: "Göteborg", text: "IPTV Göteborg — optimisé pour la Suède occidentale. Suivez IFK Göteborg et tout le sport suédois (Allsvenskan, SHL), plus chaînes internationales. Diffusé via CDN nordique." },
        { name: "Malmö", text: "IPTV Malmö — idéal pour les utilisateurs cherchant des chaînes arabes, turques, ExYu ou internationales en plus du contenu suédois. Plus grande gamme multilingue de Suède." },
        { name: "Uppsala", text: "IPTV Uppsala — parfait pour étudiants et familles. Sans engagement, fonctionne sur laptop, téléphone et TV. Streaming stable via Bahnhof et fibre universitaire." },
        { name: "Västerås", text: "IPTV Västerås — solution stable avec installation facile via WhatsApp et support complet en suédois. SVT, TV4, sport et 20 000+ chaînes internationales." },
        { name: "Linköping", text: "IPTV Linköping — pour les foyers qui veulent tout au même endroit. Allsvenskan, SHL, Premier League et chaînes suédoises en 4K UHD." },
        { name: "Örebro", text: "IPTV Örebro — choix parfait pour les foyers d'Örebro. TV suédoise complète plus 19 langues pour familles multilingues." },
        { name: "Helsingborg", text: "IPTV Helsingborg — choix premium pour le sud de la Suède. Chaînes suédoises, danoises (DR1, TV2), allemandes et britanniques." },
      ],
    },
    setup: {
      title: "Installation rapide — 10 minutes sur Firestick ou Smart TV",
      sub: "Fonctionne sur Firestick, Samsung Smart TV, LG, iPhone, Android, MAG Box. Nous vous guidons en suédois, anglais ou français.",
      button: "Obtenir de l'aide maintenant",
      steps: [
        { step: "1", text: "Contactez-nous sur WhatsApp — indiquez votre appareil (Firestick, Samsung TV, etc)." },
        { step: "2", text: "Choisissez votre offre et payez via Swish, BankID ou Klarna." },
        { step: "3", text: "Recevez votre lien M3U et guide d'installation — commencez à regarder en 10 minutes." },
      ],
    },
    footer: {
      rights: "Tous droits réservés.",
      note: "Optimisé pour streaming rapide et stable dans toute la Suède. Serveurs à Stockholm et Helsinki.",
      legal: "Mentions légales",
      privacy: "Politique de confidentialité",
      terms: "Conditions d'utilisation",
      refund: "Politique de satisfaction",
    },
    whatsapp: {
      generic: "Bonjour ! J'ai besoin d'aide avec Sverige TV.",
      trial: "Bonjour ! Je voudrais tester Sverige TV gratuitement pendant 24h. Pouvez-vous m'aider ?",
      orderMessage: (p, pr, c) => `Bonjour ! Je veux commander ${p} (${pr} ${c}). Pouvez-vous m'aider ?`,
    },
    bot: {
      greeting1: "Bonjour ! 👋 Je suis Moa.",
      greeting2: "Je peux vous aider avec les offres, l'essai gratuit ou l'installation. Que souhaitez-vous savoir ?",
      price1: "Nos offres vont de 50 kr/mois — 1, 3, 6 ou 12 mois. Toutes incluent 20 000+ chaînes et EPG.",
      price2: "Voulez-vous voir les offres, ou essayer gratuitement 24h d'abord ?",
      install1: "Firestick et Smart TV sont nos appareils les plus populaires — l'installation prend 10 minutes.",
      install2: "Je vous envoie un guide d'installation étape par étape directement sur WhatsApp !",
      trial1: "Absolument ! Nous offrons un essai gratuit de 24 heures — sans carte bancaire.",
      trial2: "Cliquez ci-dessous et je vous envoie le lien d'essai directement sur WhatsApp.",
      default1: "Je peux aider avec les offres, l'essai gratuit, l'installation et la compatibilité.",
      default2: "Pour une aide rapide — contactez-moi sur WhatsApp !",
      quick: ["Voir les prix 💰", "Essai gratuit 24h 🧪", "Aide Firestick 🔥", "Quelles chaînes ? 📺"],
    },
  },
};
