import type{Metadata}from"next";
export const metadata:Metadata={title:"Titta på Svensk TV Utomlands — Laglig Guide 2026 | Sverige TV",description:"Se SVT, TV4, Allsvenskan och alla svenska kanaler utomlands. Laglig IPTV för expats och resenärer. Fungerar i hela världen utan VPN."};
const countries=[{flag:"🇪🇸",name:"Spanien"},{flag:"🇹🇭",name:"Thailand"},{flag:"🇺🇸",name:"USA"},{flag:"🇬🇧",name:"England"},{flag:"🇩🇪",name:"Tyskland"},{flag:"🇫🇷",name:"Frankrike"},{flag:"🇦🇺",name:"Australien"},{flag:"🇨🇦",name:"Kanada"},{flag:"🇦🇪",name:"Dubai"},{flag:"🇯🇵",name:"Japan"},{flag:"🇳🇴",name:"Norge"},{flag:"🇫🇮",name:"Finland"}];
export default function Page(){return(<main style={{maxWidth:860,margin:"0 auto",padding:"60px 20px",color:"#f0eff0",fontFamily:"system-ui,sans-serif",background:"#060407",minHeight:"100vh"}}>
<nav style={{marginBottom:24,fontSize:13,color:"#7a7a86"}}><a href="/" style={{color:"#c8a96e",textDecoration:"none"}}>Sverige TV</a> › Svensk TV Utomlands</nav>
<h1 style={{fontSize:"clamp(1.8rem,5vw,3rem)",fontWeight:900,marginBottom:12}}>Titta på Svensk TV Utomlands</h1>
<p style={{color:"#9898a4",marginBottom:16,lineHeight:1.7,fontSize:16}}>SVT Play blockerar dig utomlands. TV4 Play fungerar inte utanför Sverige. Men med Sverige TV kan du se alla svenska kanaler var du än befinner dig — helt lagligt, utan VPN.</p>
<div style={{background:"#0d1a0d",border:"1px solid #16a34a",borderRadius:12,padding:"20px 24px",marginBottom:40}}>
<b style={{color:"#22c55e"}}>✅ Fungerar direkt i:</b>
<div style={{display:"flex",flexWrap:"wrap",gap:10,marginTop:12}}>{countries.map(c=>(<span key={c.name} style={{background:"#0b1a0b",border:"1px solid #16a34a",borderRadius:8,padding:"6px 12px",fontSize:14}}>{c.flag} {c.name}</span>))}</div></div>
<h2 style={{fontSize:"1.3rem",fontWeight:800,margin:"0 0 16px"}}>Vilka kanaler kan jag se utomlands?</h2>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:12,marginBottom:40}}>
{[["📺 SVT 1 & SVT 2","Nyheter, drama, dokumentärer"],["📺 TV4 & TV4 Play","Nyheter, underhållning, sport"],["⚽ Allsvenskan","Alla matcher live"],["🏒 SHL Hockey","Svensk ishockey live"],["🎬 100 000+ VOD","Filmer och serier"],["📡 20 000+ kanaler","Live TV från hela världen"]].map(([t,d])=>(<div key={t} style={{background:"#0b0b0d",border:"1px solid #1e1e1e",borderRadius:10,padding:"16px"}}><b style={{display:"block",marginBottom:4,fontSize:14}}>{t}</b><span style={{color:"#7a7a86",fontSize:13}}>{d}</span></div>))}</div>
<h2 style={{fontSize:"1.3rem",fontWeight:800,margin:"0 0 16px"}}>Varför fungerar Sverige TV utomlands?</h2>
<p style={{color:"#d4d4d8",lineHeight:1.8,marginBottom:32}}>Till skillnad från SVT Play och TV4 Play levererar Sverige TV innehållet via dedikerade IPTV-servrar — inte via plattformarnas egna appar med geoblockeringar. Du får din M3U-länk som fungerar globalt på alla enheter.</p>
{[["Behöver jag VPN?","Nej. Sverige TV kräver ingen VPN. Vår tjänst fungerar direkt via internet oavsett land — bara en stabil internetanslutning behövs."],["Fungerar det på hotell-WiFi?","Ja i de flesta fall. Ibland blockerar hotell-nätverk IPTV-portar. I så fall rekommenderar vi att använda mobildata istället."],["Kan jag se Allsvenskan live utomlands?","Ja! Allsvenskan, SHL, Champions League och all annan sport finns live — precis som hemma i Sverige."],["Vilken hastighet behövs?","Minst 10 Mbps för HD, 25 Mbps för 4K. De flesta moderna internetanslutningar i världen klarar detta."]].map(([q,a],i)=>(<details key={i} style={{background:"#0b0b0d",border:"1px solid #222",borderRadius:10,marginBottom:10,padding:"14px 18px"}}><summary style={{fontWeight:700,cursor:"pointer"}}>{q}</summary><p style={{marginTop:10,color:"#d4d4d8",lineHeight:1.7,fontSize:14}}>{a}</p></details>))}
<div style={{background:"#1a0a10",border:"1px solid #7c1326",borderRadius:16,padding:"32px",marginTop:48,textAlign:"center"}}><h3 style={{fontSize:"1.3rem",fontWeight:900,marginBottom:10}}>Se svensk TV var du än är — testa gratis 24h</h3><p style={{color:"#9898a4",marginBottom:24}}>Aktivering på under 10 minuter. Ingen bindningstid.</p><a href="/" style={{background:"linear-gradient(135deg,#9a1830,#7c1326)",color:"white",padding:"14px 32px",borderRadius:8,textDecoration:"none",fontWeight:800,display:"inline-block"}}>Se våra paket →</a></div>
</main>);}
