import type{Metadata}from"next";
export const metadata:Metadata={title:"IPTV på Android — Installationsguide Sverige TV 2026",description:"Installera IPTV på Android-mobil, surfplatta eller TV-box. TiviMate och IPTV Smarters steg för steg."};
export default function Page(){return(<main style={{maxWidth:800,margin:"0 auto",padding:"60px 20px",color:"#f0eff0",fontFamily:"system-ui,sans-serif",background:"#060407",minHeight:"100vh"}}>
<nav style={{marginBottom:24,fontSize:13,color:"#7a7a86"}}><a href="/" style={{color:"#c8a96e",textDecoration:"none"}}>Sverige TV</a> › <a href="/installation" style={{color:"#c8a96e",textDecoration:"none"}}>Installation</a> › Android</nav>
<h1 style={{fontSize:"clamp(1.8rem,5vw,2.8rem)",fontWeight:900,marginBottom:12}}>🤖 IPTV på Android</h1>
<p style={{color:"#9898a4",marginBottom:40,lineHeight:1.7}}>Android är den enklaste plattformen för IPTV. TiviMate och IPTV Smarters finns direkt i Play Store — installation tar under 3 minuter.</p>
<h2 style={{fontSize:"1.2rem",fontWeight:800,margin:"0 0 20px"}}>Metod 1 — TiviMate (Rekommenderas)</h2>
{[["Öppna Google Play Store","Sök efter 'TiviMate IPTV Player'"],["Installera TiviMate","Gratis version fungerar utmärkt med Sverige TV"],["Öppna TiviMate","Tryck 'Lägg till spellista' → välj 'Xtream Codes'"],["Ange dina uppgifter","Server-URL, användarnamn och lösenord från din välkomstepost"],["Klart!","Kanaler laddas in automatiskt. EPG uppdateras vid start."]].map(([t,d],i)=>(<div key={i} style={{display:"flex",gap:16,marginBottom:14,background:"#0b0b0d",border:"1px solid #1e1e1e",borderRadius:10,padding:"16px"}}>
<div style={{width:34,height:34,borderRadius:"50%",background:"linear-gradient(135deg,#9a1830,#7c1326)",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,fontSize:13,flexShrink:0}}>{i+1}</div>
<div><b style={{display:"block",marginBottom:3,fontSize:14}}>{t}</b><span style={{color:"#9898a4",fontSize:13}}>{d}</span></div></div>))}
<div style={{background:"#0d1a0d",border:"1px solid #16a34a",borderRadius:12,padding:"18px 22px",margin:"28px 0"}}>
<b style={{color:"#22c55e"}}>💡 Android TV Box</b>
<p style={{margin:"8px 0 0",color:"#d4d4d8",lineHeight:1.7,fontSize:14}}>Har du en Android TV box (Nvidia Shield, Xiaomi Mi Box, etc.)? TiviMate finns i Google Play Store — installationen är identisk. Anslut med fjärrkontrollen.</p></div>
{[["Fungerar Sverige TV på alla Android-versioner?","Android 5.0 och senare stöds. De flesta enheter från 2015 och nyare fungerar utan problem."],["TiviMate vs IPTV Smarters på Android?","Båda fungerar. TiviMate har bättre EPG och är snabbare. IPTV Smarters är enklare att konfigurera för nybörjare."],["Kan jag använda Chromecast?","Ja — du kan casta från TiviMate till en Chromecast-kompatibel TV direkt från appen."]].map(([q,a],i)=>(<details key={i} style={{background:"#0b0b0d",border:"1px solid #222",borderRadius:10,marginBottom:10,padding:"14px 18px"}}><summary style={{fontWeight:700,cursor:"pointer"}}>{q}</summary><p style={{marginTop:10,color:"#d4d4d8",lineHeight:1.7,fontSize:14}}>{a}</p></details>))}
<div style={{background:"#1a0a10",border:"1px solid #7c1326",borderRadius:14,padding:"28px",marginTop:36,textAlign:"center"}}><h3 style={{fontWeight:900,marginBottom:8}}>Behöver du hjälp med Android-installation?</h3><p style={{color:"#9898a4",marginBottom:20}}>Vi hjälper dig via WhatsApp — steg för steg.</p><a href="https://wa.me/447307410512?text=Hej!+Jag+behöver+hjälp+med+IPTV+på+Android." target="_blank" rel="noreferrer" style={{background:"#22c55e",color:"#000",padding:"14px 28px",borderRadius:8,textDecoration:"none",fontWeight:800}}>💬 WhatsApp-support</a></div>
</main>);}
