import type{Metadata}from"next";
export const metadata:Metadata={title:"IPTV på LG Smart TV — Installationsguide 2026 | Sverige TV",description:"Installera IPTV på LG Smart TV med webOS. SS IPTV från LG Content Store. Steg-för-steg guide för alla LG-modeller."};
export default function Page(){return(<main style={{maxWidth:800,margin:"0 auto",padding:"60px 20px",color:"#f0eff0",fontFamily:"system-ui,sans-serif",background:"#060407",minHeight:"100vh"}}>
<nav style={{marginBottom:24,fontSize:13,color:"#7a7a86"}}><a href="/" style={{color:"#c8a96e",textDecoration:"none"}}>Sverige TV</a> › <a href="/installation" style={{color:"#c8a96e",textDecoration:"none"}}>Installation</a> › LG Smart TV</nav>
<h1 style={{fontSize:"clamp(1.8rem,5vw,2.8rem)",fontWeight:900,marginBottom:12}}>🖥️ IPTV på LG Smart TV</h1>
<p style={{color:"#9898a4",marginBottom:40,lineHeight:1.7}}>LG Smart TV med webOS stöder SS IPTV — en gratis app från LG Content Store. Installation tar under 10 minuter.</p>
<h2 style={{fontSize:"1.2rem",fontWeight:800,margin:"0 0 20px"}}>Metod 1 — SS IPTV (Rekommenderas)</h2>
{[["Öppna LG Content Store","Tryck på Home-knappen → LG Content Store"],["Sök 'SS IPTV'","Installera SS IPTV gratis"],["Öppna SS IPTV","Anteckna koden som visas på skärmen"],["Aktivera via dator","Gå till ssiptv.app på din dator — ange TV-koden"],["Lägg till spellista","Ange din M3U-URL från Sverige TV och spara"],["Klart!","Återgå till TV:n — kanalerna laddas automatiskt"]].map(([t,d],i)=>(<div key={i} style={{display:"flex",gap:16,marginBottom:14,background:"#0b0b0d",border:"1px solid #1e1e1e",borderRadius:10,padding:"16px"}}>
<div style={{width:34,height:34,borderRadius:"50%",background:"linear-gradient(135deg,#9a1830,#7c1326)",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,fontSize:13,flexShrink:0}}>{i+1}</div>
<div><b style={{display:"block",marginBottom:3,fontSize:14}}>{t}</b><span style={{color:"#9898a4",fontSize:13}}>{d}</span></div></div>))}
<div style={{background:"#1a0a10",border:"1px solid #9a1830",borderRadius:12,padding:"18px 22px",margin:"28px 0"}}>
<b style={{color:"#c8a96e"}}>💡 Alternativ: Firestick via HDMI</b>
<p style={{margin:"8px 0 0",color:"#d4d4d8",lineHeight:1.7,fontSize:14}}>Vill du ha TiviMate och bättre upplevelse? Anslut en Firestick 4K till HDMI-porten på din LG TV. Byt inmatningskälla till HDMI och installera TiviMate på Firestick — överlägset bästa upplevelsen.</p></div>
{[["Hittar jag inte SS IPTV i LG Content Store?","Tillgängligheten varierar per region och TV-modell. Prova att söka på 'IPTV' i Content Store. Alternativt, använd Firestick via HDMI."],["Fungerar det på äldre LG-modeller?","LG Smart TV med webOS 3.0 (2016) och senare stöder SS IPTV. Äldre modeller rekommenderas Firestick via HDMI."],["Hur anger jag M3U-länken?","M3U-länken får du i välkomstmailen från Sverige TV. Kopiera den exakt till ssiptv.app-portalen på din dator."]].map(([q,a],i)=>(<details key={i} style={{background:"#0b0b0d",border:"1px solid #222",borderRadius:10,marginBottom:10,padding:"14px 18px"}}><summary style={{fontWeight:700,cursor:"pointer"}}>{q}</summary><p style={{marginTop:10,color:"#d4d4d8",lineHeight:1.7,fontSize:14}}>{a}</p></details>))}
<div style={{background:"#1a0a10",border:"1px solid #7c1326",borderRadius:14,padding:"28px",marginTop:36,textAlign:"center"}}><h3 style={{fontWeight:900,marginBottom:8}}>Hjälp med LG-installation?</h3><p style={{color:"#9898a4",marginBottom:20}}>Vi guidar dig steg för steg via WhatsApp.</p><a href="https://wa.me/447307410512?text=Hej!+Jag+behöver+hjälp+med+IPTV+på+LG+Smart+TV." target="_blank" rel="noreferrer" style={{background:"#22c55e",color:"#000",padding:"14px 28px",borderRadius:8,textDecoration:"none",fontWeight:800}}>💬 WhatsApp-support</a></div>
</main>);}
