import type{Metadata}from"next";
export const metadata:Metadata={title:"IPTV på iPhone och iPad — Installationsguide 2026 | Sverige TV",description:"Installera IPTV Smarters Pro på iPhone eller iPad. Steg-för-steg guide för iOS. Igång på 5 minuter med Sverige TV."};
export default function Page(){return(<main style={{maxWidth:800,margin:"0 auto",padding:"60px 20px",color:"#f0eff0",fontFamily:"system-ui,sans-serif",background:"#060407",minHeight:"100vh"}}>
<nav style={{marginBottom:24,fontSize:13,color:"#7a7a86"}}><a href="/" style={{color:"#c8a96e",textDecoration:"none"}}>Sverige TV</a> › <a href="/installation" style={{color:"#c8a96e",textDecoration:"none"}}>Installation</a> › iPhone</nav>
<h1 style={{fontSize:"clamp(1.8rem,5vw,2.8rem)",fontWeight:900,marginBottom:12}}>📱 IPTV på iPhone och iPad</h1>
<p style={{color:"#9898a4",marginBottom:40,lineHeight:1.7}}>IPTV Smarters Pro finns gratis i App Store och är den enklaste vägen till Sverige TV på din iPhone eller iPad. Installation tar under 5 minuter.</p>
<h2 style={{fontSize:"1.2rem",fontWeight:800,margin:"0 0 20px"}}>Steg-för-steg installation</h2>
{[["Öppna App Store","Sök efter 'IPTV Smarters Pro' — ladda ner gratis"],["Öppna appen","Tryck 'Add User' eller 'Lägg till konto'"],["Välj inloggningsmetod","Välj 'Xtream Codes API' för enklaste installation"],["Ange dina uppgifter","Server-URL, användarnamn och lösenord från välkomstmailen"],["Ladda kanaler","Tryck 'Lägg till' — kanalerna laddas in på ca 30 sekunder"],["Se på TV!","Välj kategori, välj kanal — perfekt bild direkt"]].map(([t,d],i)=>(<div key={i} style={{display:"flex",gap:16,marginBottom:14,background:"#0b0b0d",border:"1px solid #1e1e1e",borderRadius:10,padding:"16px"}}>
<div style={{width:34,height:34,borderRadius:"50%",background:"linear-gradient(135deg,#9a1830,#7c1326)",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,fontSize:13,flexShrink:0}}>{i+1}</div>
<div><b style={{display:"block",marginBottom:3,fontSize:14}}>{t}</b><span style={{color:"#9898a4",fontSize:13}}>{d}</span></div></div>))}
<div style={{background:"#0d1a0d",border:"1px solid #16a34a",borderRadius:12,padding:"18px 22px",margin:"28px 0"}}>
<b style={{color:"#22c55e"}}>💡 Apple TV</b>
<p style={{margin:"8px 0 0",color:"#d4d4d8",lineHeight:1.7,fontSize:14}}>Har du Apple TV 4K? IPTV Smarters Pro finns även i tvOS App Store. Samma inloggningsuppgifter fungerar — perfekt för storbildsskärmen.</p></div>
{[["Finns TiviMate för iPhone?","Nej — TiviMate är exklusivt för Android. På iPhone är IPTV Smarters Pro det bästa alternativet."],["Kan jag se i bakgrunden medan jag gör annat?","Ja — iOS stöder bild-i-bild (PiP) så du kan se TV medan du använder andra appar."],["Fungerar det på WiFi och mobildata?","Ja, båda fungerar. 10 Mbps för HD, 25 Mbps för 4K. Mobildata fungerar bra om du har 4G/5G."]].map(([q,a],i)=>(<details key={i} style={{background:"#0b0b0d",border:"1px solid #222",borderRadius:10,marginBottom:10,padding:"14px 18px"}}><summary style={{fontWeight:700,cursor:"pointer"}}>{q}</summary><p style={{marginTop:10,color:"#d4d4d8",lineHeight:1.7,fontSize:14}}>{a}</p></details>))}
<div style={{background:"#1a0a10",border:"1px solid #7c1326",borderRadius:14,padding:"28px",marginTop:36,textAlign:"center"}}><h3 style={{fontWeight:900,marginBottom:8}}>Hjälp med iPhone-installation?</h3><p style={{color:"#9898a4",marginBottom:20}}>Vår support guidar dig via WhatsApp på 5 minuter.</p><a href="https://wa.me/447307410512?text=Hej!+Jag+behöver+hjälp+med+IPTV+på+iPhone." target="_blank" rel="noreferrer" style={{background:"#22c55e",color:"#000",padding:"14px 28px",borderRadius:8,textDecoration:"none",fontWeight:800}}>💬 WhatsApp-support</a></div>
</main>);}
